### ISSUE TITLE
If we want to use this as a live blog

### ISSUE THREAD

**Issue by LilyMihalik** [The-Politico/django-slackchat-serializer#20]
What is a live blog?

> Live blogs make it easy for readers who are intensely following a news story to know what is the latest information. Those readers don’t need to skim seven paragraphs of background information, as they might do in a traditional news article, to figure out what has changed. The latest information is right there, at the top.

 - [ ]  sticky post as needed
 - [ ]  what you need to know section?
 - [ ]  do we want an option for a breaking news ledeall
 - [ ]  pull quotes
 - [ ]  filters?
 - [ ]  might we want some sort of quick timeline nav ie:wapo’s

**Comment by brizandrew** [comment]
Moved to renderer.
