### ISSUE TITLE
Slack Chat design improvements

### ISSUE THREAD

**Issue by LilyMihalik** [The-Politico/django-slackchat-serializer#21]
People are missing the latest button
- [ ] a better solve to make this more visible = have more utility
- [ ] the top button only appears at the end of the scroll, should that be sticky so readers can get back to the top easier at any point? 
![image](https://user-images.githubusercontent.com/1634854/39840064-2c7a8a8a-53ac-11e8-9459-19e65b12d865.png)

**Comment by brizandrew** [comment]
Moved to renderer.
